[package]
name = "tokio-signal"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/tokio-signal"
homepage = "https://github.com/alexcrichton/tokio-signal"
documentation = "https://alexcrichton.github.io/tokio-signal"
description = """
An implementation of an asynchronous Unix signal handling backed futures.
"""

[dependencies]
tokio-core = { git = "https://github.com/tokio-rs/tokio-core" }
futures = { git = "https://github.com/alexcrichton/futures-rs" }

[target.'cfg(unix)'.dependencies]
tokio-uds = { git = "https://github.com/tokio-rs/tokio-uds" }
libc = "0.2"
mio = "0.6"

[target.'cfg(windows)'.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"
mio = "0.6"
