[package]
name = "tokio-process"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/tokio-process"
homepage = "https://github.com/alexcrichton/tokio-process"
documentation = "https://alexcrichton.github.io/tokio-process"
description = """
An implementation of an asynchronous process management backed futures.
"""

[dependencies]
tokio-core = "0.1"
futures = "0.1.7"
mio = "0.6"
log = "0.3"

[dev-dependencies]
env_logger = { version = "0.3", default-features = false }

[target.'cfg(windows)'.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"
mio-named-pipes = "0.1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
tokio-signal = "0.1"
