[package]
name = "tokio-core"
version = "0.1.1"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/tokio-rs/tokio-core"
homepage = "https://github.com/tokio-rs/tokio-core"
documentation = "https://tokio-rs.github.io/tokio-core"
description = """
Core I/O and event loop primitives for asynchronous I/O in Rust. Foundation for
the rest of the tokio crates.
"""

[dependencies]
futures = "0.1.4"
log = "0.3"
mio = "0.6"
scoped-tls = "0.1.0"
slab = "0.3"

[dev-dependencies]
env_logger = { version = "0.3", default-features = false }
libc = "0.2"
