[workspace]

members = [
  "tokio",
  "tokio-executor",
  "tokio-macros",
  "tokio-sync",
  "tokio-test",
  "tokio-tls",
  "tokio-util",

  # Internal
  "examples",
  "tests-build",
  "tests-integration",
]
