jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ubuntu-16.04

  steps:
  - template: azure-install-rust.yml
    parameters:
      rust_version: ${{ parameters.rust }}

  - template: azure-patch-crates.yml

  - script: cargo test
    displayName: cargo +nightly test -p async-await
    workingDirectory: $(Build.SourcesDirectory)/async-await

  - script: cargo check --all
    displayName: cargo +nightly check --all

  # Check benches
  - script: cargo check --benches --all
    displayName: Check benchmarks
