name: "Pull Request Labeler"
on:
- pull_request_target

# See .github/labeler.yml file

jobs:
  triage:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'tokio-rs'
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
